server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: Sharma123@
  application:
    name: userauthentication-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerEureka: true

