server:
  port: 8082
  error:
    include-message: always
spring:
  application:
    name: vehicle-service
  data:
    mongodb:
      database: ecommerce
      uri: mongodb://localhost:27017/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerEureka: true

